from src.tracesynth.synth.memory_relation import *
from src.tracesynth.synth.ppo_def import *
from src.tracesynth.synth.ppo_dict import SinglePPO
from src.tracesynth.synth.ppo_dict import PPOPool


def get_rvwmo_sc_per_location_model():
    RVWMO_model = PPOPool()
    ppo1_1 = SinglePPO([R(), PoLoc(), W()])
    ppo1_2 = SinglePPO([W(), PoLoc(), W()])
    ppo2_1 = SinglePPO([R(), PoLoc(), R()])
    ppo4_1 = SinglePPO([R(), FenceD(FenceAnnotation.R_R), R()])
    ppo4_2 = SinglePPO([R(), FenceD(FenceAnnotation.R_W), W()])
    ppo4_3 = SinglePPO([R(), FenceD(FenceAnnotation.R_RW), R()])
    ppo4_4 = SinglePPO([R(), FenceD(FenceAnnotation.R_RW), W()])
    ppo4_5 = SinglePPO([W(), FenceD(FenceAnnotation.W_R), R()])
    ppo4_6 = SinglePPO([W(), FenceD(FenceAnnotation.W_W), W()])
    ppo4_7 = SinglePPO([W(), FenceD(FenceAnnotation.W_RW), W()])
    ppo4_8 = SinglePPO([W(), FenceD(FenceAnnotation.W_RW), R()])
    ppo4_9 = SinglePPO([R(), FenceD(FenceAnnotation.RW_R), R()])
    ppo4_10 = SinglePPO([W(), FenceD(FenceAnnotation.RW_R), R()])
    ppo4_11 = SinglePPO([R(), FenceD(FenceAnnotation.RW_W), W()])
    ppo4_12 = SinglePPO([W(), FenceD(FenceAnnotation.RW_W), W()])
    ppo4_13 = SinglePPO([R(), FenceD(FenceAnnotation.RW_RW), W()])
    ppo4_14 = SinglePPO([W(), FenceD(FenceAnnotation.RW_RW), R()])
    ppo4_15 = SinglePPO([W(), FenceD(FenceAnnotation.RW_RW), W()])
    ppo4_16 = SinglePPO([R(), FenceD(FenceAnnotation.RW_RW), R()])
    ppo4_17 = SinglePPO([W(), FenceD(FenceAnnotation.TSO), W()])
    ppo4_18 = SinglePPO([R(), FenceD(FenceAnnotation.TSO), W()])
    ppo4_19 = SinglePPO([R(), FenceD(FenceAnnotation.TSO), R()])
    RVWMO_model.add_ppo(ppo1_1, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo1_2, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo2_1, ppo_init_flag=PPOInitFlag.Verified)
    RVWMO_model.add_ppo(ppo4_1, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_2, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_3, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_4, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_5, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_6, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_7, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_8, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_9, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_10, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_11, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_12, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_13, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_14, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_15, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_16, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_17, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_18, ppo_init_flag=PPOInitFlag.Init)
    RVWMO_model.add_ppo(ppo4_19, ppo_init_flag=PPOInitFlag.Init)

    return RVWMO_model